//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "classes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub teacher_id: Uuid,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub students_classes: HasMany<super::students_classes::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Serialize, Deserialize, DeriveIntoActiveModel)]
pub struct Required {
    pub name: String,
    pub description: Option<String>,
}

