//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "students_classes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub class_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub student_id: Uuid,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "class_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub classes: HasOne<super::classes::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
